### ISSUE TITLE
MangoDB is not set

### ISSUE THREAD

**Issue by Nathanmalnoury** [EBM2018/teamy#17]
To be set : 
- on the server
- on the docket compose 
- on dockerfile

**Comment by nymous** [comment]
You can look at this docker-compose https://github.com/EBM-2017-2018/linkapp/blob/master/docker-compose.yml.

Important bits (I extracted the lines you need to add/merge/uncomment to your existing compose file):
```yaml
services:
  web:
    environment:
      # Your .env file should have a variable with the connection URL string, this replaces it
      # syntax is mongodb://<hostname of mongodb, aka service name (for you it's mongodb)>/<name of the collection to create>
      - MONGODB_URI=mongodb://mongodb/node-auth

  # Create a new service in the compose file for the DB container
  # you can call it whatever you want, but report this name in the connection URL above
  mongodb:
    image: mongo
    # mongodb should only be accessible from containers in this compose file, eg. the web service, so we put it on the local network
    networks:
      - local
    # mount a persistent volume managed by docker in the directory used by mongodb to store its data
    volumes:
      - mongo-volume:/data/db

# Tell docker-compose it should create and manage a volume named mongo-volume
volumes:
  mongo-volume:
```
